defaults:
  - user: single_user
  - transforms: log_spectrogram
  - cluster: local
  - _self_

seed: 1501
batch_size: 32
num_workers: 4

fusion_module:
  acoustic_checkpoint: ???  # required: path to frozen acoustic model checkpoint
  lm_path: ${hydra:runtime.cwd}/models/lm/wikitext-103-6gram-charlm.bin
  n_beams: 10
  hidden_dim: 64
  lr: 1e-3
  beam_size: 50

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  default_root_dir: ${hydra:runtime.output_dir}

callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${hydra:runtime.output_dir}/checkpoints
    monitor: val/CER
    mode: min
    save_last: True
    verbose: True

dataset:
  root: ${hydra:runtime.cwd}/data

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: hydra_configs
  job:
    name: emg2qwerty_fusion
